key:
  mcName: Validation
  pathResult: /home/developer/dev/shevchenko/git/mctester/
kafka:
  bootstrapAddress: localhost:9092
  groupId: sphinx
  groupPr: shp_pr
  topics:
    in: incoming
    out: outcoming
server:
  port: 7777
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: chains