key:
  mcName: Validation
  pathResult: /home/developer/dev/shevchenko/git/mctester/
kafka:
  bootstrapAddress: localhost:9092
  groupId: sphinx_consumer
  groupPr: sphinx_producer
server:
  port: 7777
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: chains