server:
  port: 7777
spring:
  application:
    name: sphinx
    description: Application for testing microservice in test stand
    repo: test
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: chains